# Generated by Django 5.1.3 on 2024-12-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
