# Generated by Django 5.1.3 on 2024-12-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_data_joined_employee_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Employee of the task.', related_name='tasks', to='api.employee'),
        ),
    ]
